name: Bao misc workflow

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  pylint:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - run: >
          make pylint

  yamllint:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - run: >
          make yamllint
